name: puppeteer
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pytorch
  - torchvision
  - cudatoolkit=11.7
  - glew
  - glib
  - pip==21
  - pip:
    - absl-py
    - glfw
    - kornia
    - termcolor
    - gym==0.21.0
    - shimmy>=0.2.1
    - git+https://github.com/microsoft/MoCapAct.git
    - moviepy
    - ffmpeg
    - imageio
    - imageio-ffmpeg
    - omegaconf
    - hydra-core
    - hydra-submitit-launcher
    - submitit
    - scikit-learn
    - pyarrow
    - pandas
    - patchelf
    - protobuf
    - tqdm
    - joblib
    - opencv-python
    - opencv-contrib-python
    - filelock
    - setuptools==65.5.0
    - "cython<3"
    - mujoco==2.3.1
    - mujoco-py==2.1.2.14
    - dm-control
    - pillow
    - tensordict-nightly==2024.3.26
    - torchrl-nightly==2024.3.26
    - wandb
